name:                localcooking-function
version:             0.0.0
git:                 "git://git.localcooking.com:localcooking/localcooking-function.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/localcooking-function#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  localcooking-function-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-function

tests:
  localcooking-function-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-function
