name:                localcooking-function
version:             0.0.0
git:                 "git://git.localcooking.com:localcooking/localcooking-function.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/localcooking-function#readme>

ghc-options:
  - -Wall

dependencies:
- localcooking-shared
- localcooking-fb
- localcooking-db
- base >= 4.7 && < 5
- aeson
- async
- attoparsec-uri >= 0.0.4
- bytestring
- containers
- data-default
- emailaddress >= 0.2.0.1
- hashable
- http-client
- http-client-tls
- monad-control
- monad-control-aligned
- monad-logger
- monad-unlift
- mtl
- newtype
- persistent
- persistent-postgresql
- resource-pool
- stm
- strict
- text
- time
- timemap >= 0.0.7
- tmapmvar
- transformers-base
- unordered-containers
- unliftio-core
- utf8-string

library:
  source-dirs: src

tests:
  localcooking-function-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-function
